version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: lanidrac_postgres
    environment:
      POSTGRES_DB: lanidrac
      POSTGRES_USER: lanidrac_user
      POSTGRES_PASSWORD: lanidrac_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: